### ISSUE TITLE
Texture rework

### ISSUE THREAD

**Issue by omnit3a** [PQCraft/CaveCube#3]
I would suggest remaking the textures like the stone texture to look less smooth, to better match the grass texture

**Comment by PQCraft** [comment]
@omnit3a i would, however i've already redone the stone texture like 3 times now lol
Also imo it doesn't look the best if it's not somewhat smooth (it's kind of purposely smooth the match the bedrock texture).
But this is an open source project so feel free to replace the images or create a texture pack. Once i add a UI, i'll get around to adding a mod and resource pack manager to make it easy to manage them. For right now, you'll have to do some DWM-style magic and edit the code in `src/common/resource.c` to have it manually add the pack.
