### ISSUE TITLE
List of short term goals

### ISSUE THREAD

**Issue by omnit3a** [PQCraft/CaveCube#4]
Hi, I was planning on helping with this project, and I'm wondering what the short term goals of the project are? Like, what is currently being working on or planned? Also, do you have discord?

**Comment by PQCraft** [comment]
I will add my `progress.txt` to the commit list 👍

**Comment by PQCraft** [comment]
Also there is no Discord server for this project since it's too small. I do though run a Linux Discord server called The Linux Space.

**Comment by PQCraft** [comment]
@omnit3a Added (check `dev` branch) :+1:
