### ISSUE TITLE
Windows MSYS2

### ISSUE THREAD

**Issue by ruanjiashing** [PQCraft/CaveCube#8]
It seems the dev doesn't know about it. MSYS2 is a build environment for Windows that's very similar to Arch Linux (it also uses the pacman package manager). Currently there is no support for MSYS2 in the makefile, so I used this a bit hacky way to build it.

First, open the MSYS2 MINGW64 Shell.

Install toolchain: `pacman -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-make`

To build with GLFW:

`pacman -S mingw-w64-x86_64-glfw`

Then: `make WINCROSS=y WINDRES=windres STRIP=strip -j4`

To build with SDL2 (not yet work):

```
pacman -S mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_gfx \
mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_mixer \
mingw-w64-x86_64-SDL2_net mingw-w64-x86_64-SDL2_ttf \
mingw-w64-x86_64-smpeg2
```

Then: `make USESDL2=y WINCROSS=y WINDRES=windres STRIP=strip -j4`

Note: because there is no support for the MSYS2 environment yet, I have to let it assume it's cross compiling. I have to specify the `WINDRES` and `STRIP` binary too because on MSYS2 MINGW64 there is no such thing as `x86_64-w64-mingw32-windres` and `x86_64-w64-mingw32-strip`. I have no idea why because they are available on normal MinGW distributions like winlibs.com. Anyway, it's the decision of the MSYS2 package maintainers to not include these binaries so we can't do anything about it.

The build with GLFW succeeded but the build with SDL2 failed at linking:

```
Building cavecube.exe...
make[2]: [C:\msys64\tmp\ccLy8pCz.mk:3: C:\msys64\tmp\ccS5RYJl.ltrans0.ltrans.o] Error 1 (ignored)
make[2]: [C:\msys64\tmp\ccLy8pCz.mk:9: C:\msys64\tmp\ccS5RYJl.ltrans2.ltrans.o] Error 1 (ignored)
make[2]: [C:\msys64\tmp\ccLy8pCz.mk:6: C:\msys64\tmp\ccS5RYJl.ltrans1.ltrans.o] Error 1 (ignored)
```

I have no idea why it's failing.

**Comment by 3oheicrw** [comment]
Another note: currently `make clean` doesn't work, so I have to remove `cavecube.exe` and `obj` directory manually.

**Comment by PQCraft** [comment]
Ah I only meant this to be compiled with plain MinGW lol
I put some instructions in the readme of an old program of mine: https://github.com/PQCraft/CLIBASIC:
>#### Windows <br>
>NT - 10 (download): [`MinGW`](http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download), [`Make for Windows`](http://gnuwin32.sourceforge.net/packages/make.htm) <br>

>Make sure the bin folders of MinGW and Make are in the %PATH%. <br>
Type `gcc --version` into CMD and if you received a "Can't recognize" message, MinGW is not in your %PATH%. <br>
Type `make --version` into CMD and if you received a "Can't recognize" message, Make is not in your %PATH%. <br>
How to add MinGW and/or Make to the %PATH%: <br>
>1. Navigate to where MinGW or Make is installed
>2. <ins>For MinGW</ins>, open the `mingw64` folder
>3. Open the `bin` folder
>4. Copy the location
>5. Add the location you copied to the %PATH% environment variable
>    - For Windows 7 and older
>        1. Open the Start Menu
>        2. Right-click on Computer and click Properties
>        3. Click Advanced system settings
>        4. Click the Advanced tab
>        5. Click Environment Variables
>        6. Under System variables, find Path and click Edit
>        7. Add the copied location
>    - For Windows 8 and newer
>        1. Open the Start Menu
>        2. Search for and run 'Edit the system environment variables'
>        3. Click Environment Variables
>        4. Under System variables, find Path and click Edit
>        5. Add the copied location

**Comment by PQCraft** [comment]
I will see about adding a `MSYS2` variable to the makefile

**Comment by PQCraft** [comment]
> The build with GLFW succeeded but the build with SDL2 failed at linking:
>
>```
>Building cavecube.exe...
>make[2]: [C:\msys64\tmp\ccLy8pCz.mk:3: C:\msys64\tmp\ccS5RYJl.ltrans0.ltrans.o] Error 1 (ignored)
>make[2]: [C:\msys64\tmp\ccLy8pCz.mk:9: C:\msys64\tmp\ccS5RYJl.ltrans2.ltrans.o] Error 1 (ignored)
>make[2]: [C:\msys64\tmp\ccLy8pCz.mk:6: C:\msys64\tmp\ccS5RYJl.ltrans1.ltrans.o] Error 1 (ignored)
>```

Also I get this when building using Windows but it still spits out a binary so it should be fine.

**Comment by ruanjiashing** [comment]
> Ah I only meant this to be compiled with plain MinGW lol I put some instructions in the readme of an old program of mine: https://github.com/PQCraft/CLIBASIC:
> 
> > #### Windows 
> > NT - 10 (download): [`MinGW`](http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download), [`Make for Windows`](http://gnuwin32.sourceforge.net/packages/make.htm)
> 
> > Make sure the bin folders of MinGW and Make are in the %PATH%. 
> > Type `gcc --version` into CMD and if you received a "Can't recognize" message, MinGW is not in your %PATH%. 
> > Type `make --version` into CMD and if you received a "Can't recognize" message, Make is not in your %PATH%. 
> > How to add MinGW and/or Make to the %PATH%: 
> > 
> > 1. Navigate to where MinGW or Make is installed
> > 2. For MinGW, open the `mingw64` folder
> > 3. Open the `bin` folder
> > 4. Copy the location
> > 5. Add the location you copied to the %PATH% environment variable
> >    
> >    * For Windows 7 and older
> >      
> >      1. Open the Start Menu
> >      2. Right-click on Computer and click Properties
> >      3. Click Advanced system settings
> >      4. Click the Advanced tab
> >      5. Click Environment Variables
> >      6. Under System variables, find Path and click Edit
> >      7. Add the copied location
> >    * For Windows 8 and newer
> >      
> >      1. Open the Start Menu
> >      2. Search for and run 'Edit the system environment variables'
> >      3. Click Environment Variables
> >      4. Under System variables, find Path and click Edit
> >      5. Add the copied location

gnuwin32 is seriously outdated. You should consider switching to MSYS2 as it's the most feature complete solution now. But if you only want gnu make (does mingw32-make works for you? it's already a part of any standard MinGW distro so no need to install), you could download a more modern version of gnu make (not mingw32-make) here: http://www.equation.com/servlet/equation.cmd?fa=make :smile:

**Comment by ruanjiashing** [comment]
BTW, I found you are still using the MinGW version from sourceforge. It's also seriously outdated and not updated for many years. To download latest MinGW, go to this site: winlibs.com :smile:

**Comment by PQCraft** [comment]
Ah it was something that just worked:tm: lol

**Comment by PQCraft** [comment]
When making binaries for Windows though, I use the cross compiler (I'm on Arch Linux) but when I need to test Windows builds specifically, I'll open wineconsole and punch in some commands

**Comment by PQCraft** [comment]
I still want to keep MinGW support since it's pretty portable (I have a portable MinGW folder on a USB for when I need to compile something on a Windows machine), but I will see about adding MSYS2 support by passing `MSYS2=y` to the Makefile

**Comment by ruanjiashing** [comment]
> I still want to keep MinGW support since it's pretty portable (I have a portable MinGW folder on a USB for when I need to compile something on a Windows machine), but I will see about adding MSYS2 support by passing `MSYS2=y` to the Makefile

Yeah, MSYS2 and MinGW is a different thing. I didn't ask you to move to MSYS2. The site winlibs.com I give you is about downloading standalone MinGW. MinGW could be used standalone or with MSYS2 (MSYS2 has it own version of MinGW that you could install using the pacman package manager, but if you want to use the standalone MinGW from winlibs.com then it's also works).

**Comment by PQCraft** [comment]
Ok I am going to have to do a bit of tomfoolery with this now. MSYS2 refuses to run under wine (the installer gets stuck at 66% and killing the hung process finishes the install, but when starting any of the exes, it throws some error about not being able to fork). I think this is due to them using Cygwin which afaik is pretty crusty and uses a lot of hacks. I'll have to use my VM to do everything which means a lot of copying around files and dealing with Windows 7 console crust.

**Comment by ruanjiashing** [comment]
> Ok I am going to have to do a bit of tomfoolery with this now. MSYS2 refuses to run under wine (the installer gets stuck at 66% and killing the hung process finishes the install, but when starting any of the exes, it throws some error about not being able to fork). I think this is due to them using Cygwin which afaik is pretty crusty and uses a lot of hacks.

If you tell me you are going to run it under wine I could tell you think this will not work from the beginning. You are basically trying to run a compatibility layer on top of another compatibility layer. It of course doesn't work.

> I'll have to use my VM to do everything which means a lot of copying around files and dealing with Windows 7 console crust.

You don't have to care about this. MSYS2 (and so does Cygwin) uses the Mintty terminal emulator and it's much better than Windows Command Prompt, just remember to open the MSYS2 MINGW64 Shell from Start Menu. Note: it will install 5 shells which is 5 different build environment: MSYS2 MSYS (same as Cygwin), MSYS2 MINGW32, MSYS2 MINGW64, MSYS2 CLANG64 and MSYS2 UCRT64.

**Comment by PQCraft** [comment]
It now compiles successfully under MSYS2 when passing `MSYS2=y` and I added build instructions (check the `dev` branch to see the changes). The game is currently in a broken state though since I'm currently working on redoing the UI code.
