### ISSUE TITLE
Support build with Pelles C

### ISSUE THREAD

**Issue by ghost** [PQCraft/CaveCube#9]
Pelles C runs well on wine: http://www.smorgasbordet.com/pellesc/

**Comment by PQCraft** [comment]
I use GCC extensions so this would not be possible.

**Comment by ghost** [comment]
> I use GCC extensions so this would not be possible.

Pelles C supports some GCC extensions with the /Zx option.

**Comment by PQCraft** [comment]
Yeah but it's not really necessary since you can just use MinGW or MSYS2.

**Comment by PQCraft** [comment]
Plus I use GNU make for the build system. If you look in the makefiles, you can see that it's pretty specialized and IMO, it's not really worth rewriting the build system when there's no reason to.

**Comment by ghost** [comment]
> Plus I use GNU make for the build system. If you look in the makefiles, you can see that it's pretty specialized and IMO, it's not really worth rewriting the build system when there's no reason to.

Pelles C command line utilities could be used with make too. The same way people using MSVC cl.exe with make.

**Comment by ghost** [comment]
> Yeah but it's not really necessary since you can just use MinGW or MSYS2.

Yeah I understand :smile:
